import { Category, Product } from '../types';

export const categories: Category[] = [
  { id: 'c1', name: 'Imperdibles Clásicas', slug: 'imperdibles-clasicas', order: 1, imageUrl: '/images/categories/cat-clasicas.jpg' },
  { id: 'c2', name: 'Para Compartir', slug: 'para-compartir', order: 2, imageUrl: '/images/categories/cat-compartir.jpg' },
  { id: 'c3', name: 'Formatos Clásicos', slug: 'formatos-clasicos', order: 3, imageUrl: '/images/categories/cat-formatos.jpg' },
  { id: 'c4', name: 'Promos Especiales', slug: 'promos-especiales', order: 4, imageUrl: '/images/categories/cat-promos.jpg' },
  { id: 'c5', name: 'Promos Premium', slug: 'promos-premium', order: 5, imageUrl: '/images/categories/cat-premium.jpg' },
  { id: 'c6', name: 'Arma Tu Roll', slug: 'arma-tu-roll', order: 6, imageUrl: '/images/categories/cat-arma.jpg' },
  { id: 'c7', name: 'Clasi Combos', slug: 'clasi-combos', order: 7, imageUrl: '/images/categories/cat-combos.jpg' },
  { id: 'c8', name: 'Bebestibles', slug: 'bebestibles', order: 8, imageUrl: '/images/categories/cat-bebestibles.jpg' },
];

export const products: Product[] = [
  // ============================================
  // 🍱 IMPERDIBLES CLÁSICAS (c1)
  // ============================================
  // Promociones Individuales y en Pareja
  {
    id: 'p1_1',
    categoryId: 'c1',
    name: 'Promo Individual 1',
    description: '1 Handroll Pollo, 1 Papas Fritas Sobre, 1 Bebida Lata 220cc. (Ahorra $2.500)',
    price: 5500,
    imageUrl: '/images/products/c1.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p1_2',
    categoryId: 'c1',
    name: 'Promo Individual 2',
    description: '1 Sushiburger Pollo, 1 Papas Fritas Sobre, 1 Bebida Lata 220cc. (Ahorra $2.500)',
    price: 8500,
    imageUrl: '/images/products/p1_2.jpg',
    prepTime: 10,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p1_3',
    categoryId: 'c1',
    name: 'Promo Pareja 1',
    description: '2 Handroll Pollo, 1 Papas Fritas Sobre, 2 Bebida Lata 220cc. (Ahorra $2.500)',
    price: 9500,
    imageUrl: '/images/products/p1_3.jpg',
    prepTime: 12,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p1_4',
    categoryId: 'c1',
    name: 'Promo Pareja 2',
    description: '2 Sushiburger Pollo, 1 Papas Fritas Sobre, 2 Bebida Lata 220cc. (Ahorra $2.500)',
    price: 15500,
    imageUrl: '/images/products/p1_4.jpg',
    prepTime: 15,
    isAvailable: true,
    isPopular: false,
  },
  // Clasi Lover
  {
    id: 'p1_5',
    categoryId: 'c1',
    name: 'Clasi Lover 1',
    description: '2 Handroll Pollo (Queso crema - Palta).',
    price: 6500,
    imageUrl: '/images/products/p1_5.jpg',
    prepTime: 8,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p1_6',
    categoryId: 'c1',
    name: 'Clasi Lover 2',
    description: '2 Sushipleto Pollo (Queso crema - Palta).',
    price: 10500,
    imageUrl: '/images/products/p1_6.jpg',
    prepTime: 14,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p1_7',
    categoryId: 'c1',
    name: 'Clasi Lover 3',
    description: '2 Sushiburger Pollo (Queso crema - Palta - Cebollín).',
    price: 12500,
    imageUrl: '/images/products/p1_7.jpg',
    prepTime: 12,
    isAvailable: true,
    isPopular: true,
  },

  // ============================================
  // 🍟 PARA COMPARTIR (c2)
  // ============================================
  // Arrollados
  {
    id: 'p2_1',
    categoryId: 'c2',
    name: 'Arrollado Jamón Queso (5 Unidades)',
    description: 'Clásicos arrollados fritos rellenos de Jamón y Queso.',
    price: 4000,
    imageUrl: '/images/products/p2_1.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p2_2',
    categoryId: 'c2',
    name: 'Arrollado Primavera (5 Unidades)',
    description: 'Clásicos arrollados primavera fritos.',
    price: 4000,
    imageUrl: '/images/products/p2_2.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: false,
  },
  // Papas Fritas
  {
    id: 'p2_3',
    categoryId: 'c2',
    name: 'Papas Fritas Sobre',
    description: 'Porción individual en sobre de papas fritas crujientes.',
    price: 2500,
    imageUrl: '/images/products/p2_3.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p2_4',
    categoryId: 'c2',
    name: 'Papas Fritas Medianas',
    description: 'Porción mediana de papas fritas crujientes.',
    price: 4000,
    imageUrl: '/images/products/p2_4.jpg',
    prepTime: 5,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p2_5',
    categoryId: 'c2',
    name: 'Salchipapas Porción',
    description: 'Deliciosa combinación de papas fritas y vienesas.',
    price: 6000,
    imageUrl: '/images/products/p2_5.jpg',
    prepTime: 5,
    isAvailable: true,
    isPopular: false,
  },
  // Bucket
  {
    id: 'p2_6',
    categoryId: 'c2',
    name: 'BKT Pollo Crispy (400gr)',
    description: 'Trozos de pollo con cobertura crispy crujiente en formato Bucket.',
    price: 7500,
    imageUrl: '/images/products/p2_6.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p2_7',
    categoryId: 'c2',
    name: 'BKT Camarón Crispy (10 unid.)',
    description: 'Camarones apanados en cobertura crispy crujiente en formato Bucket.',
    price: 7500,
    imageUrl: '/images/products/p2_7.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p2_8',
    categoryId: 'c2',
    name: 'BKT Champiñón Crispy (200gr)',
    description: 'Champiñones apanados en cobertura crispy crujiente en formato Bucket.',
    price: 7500,
    imageUrl: '/images/products/p2_8.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },

  // ============================================
  // 🍣 FORMATOS CLÁSICOS (c3)
  // ============================================
  // Hand Roll
  {
    id: 'p3_1',
    categoryId: 'c3',
    name: 'Hand Roll Pollo',
    description: 'Queso crema - Palta.',
    price: 4000,
    imageUrl: '/images/products/p3_1.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p3_2',
    categoryId: 'c3',
    name: 'Hand Roll Champiñón',
    description: 'Queso crema - Palta.',
    price: 4000,
    imageUrl: '/images/products/p3_2.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_3',
    categoryId: 'c3',
    name: 'Hand Roll Camarones',
    description: 'Queso crema - Palta.',
    price: 5000,
    imageUrl: '/images/products/p3_3.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_4',
    categoryId: 'c3',
    name: 'Hand Roll Salmón',
    description: 'Queso crema - Palta.',
    price: 5500,
    imageUrl: '/images/products/p3_4.jpg',
    prepTime: 4,
    isAvailable: true,
    isPopular: false,
  },
  // Sushipleto
  {
    id: 'p3_5',
    categoryId: 'c3',
    name: 'Sushipleto Pollo',
    description: 'Queso crema - Palta.',
    price: 6000,
    imageUrl: '/images/products/p3_5.jpg',
    prepTime: 7,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p3_6',
    categoryId: 'c3',
    name: 'Sushipleto Champiñón',
    description: 'Queso crema - Palta.',
    price: 6000,
    imageUrl: '/images/products/p3_6.jpg',
    prepTime: 7,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_7',
    categoryId: 'c3',
    name: 'Sushipleto Camarones',
    description: 'Queso crema - Palta.',
    price: 7000,
    imageUrl: '/images/products/p3_7.jpg',
    prepTime: 7,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_8',
    categoryId: 'c3',
    name: 'Sushipleto Salmón',
    description: 'Queso crema - Palta.',
    price: 8000,
    imageUrl: '/images/products/p3_8.jpg',
    prepTime: 7,
    isAvailable: true,
    isPopular: false,
  },
  // Sushi Burger
  {
    id: 'p3_9',
    categoryId: 'c3',
    name: 'Sushi Burger Pollo',
    description: 'Queso crema - Palta - Cebollín.',
    price: 7000,
    imageUrl: '/images/products/p3_9.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p3_10',
    categoryId: 'c3',
    name: 'Sushi Burger Champiñón',
    description: 'Queso crema - Palta - Cebollín.',
    price: 7000,
    imageUrl: '/images/products/p3_10.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_11',
    categoryId: 'c3',
    name: 'Sushi Burger Camarones',
    description: 'Queso crema - Palta - Cebollín.',
    price: 8000,
    imageUrl: '/images/products/p3_11.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_12',
    categoryId: 'c3',
    name: 'Sushi Burger Salmón',
    description: 'Queso crema - Palta - Cebollín.',
    price: 9000,
    imageUrl: '/images/products/p3_12.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_13',
    categoryId: 'c3',
    name: 'Sushi Burger Mixto',
    description: 'Pollo - Camarón - Queso crema - Palta.',
    price: 10000,
    imageUrl: '/images/products/p3_13.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: true,
  },
  // Gohan
  {
    id: 'p3_14',
    categoryId: 'c3',
    name: 'Gohan Pollo',
    description: 'Queso crema - Palta - Cebollín - Morrón.',
    price: 7000,
    imageUrl: '/images/products/p3_14.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_15',
    categoryId: 'c3',
    name: 'Gohan Champiñón',
    description: 'Queso crema - Palta - Cebollín - Morrón.',
    price: 7000,
    imageUrl: '/images/products/p3_15.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_16',
    categoryId: 'c3',
    name: 'Gohan Camarones',
    description: 'Queso crema - Palta - Cebollín - Morrón.',
    price: 8000,
    imageUrl: '/images/products/p3_16.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p3_17',
    categoryId: 'c3',
    name: 'Gohan Salmón',
    description: 'Queso crema - Palta - Cebollín - Morrón.',
    price: 9000,
    imageUrl: '/images/products/p3_17.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p3_18',
    categoryId: 'c3',
    name: 'Gohan Mixto',
    description: 'Pollo - Camarón - Cebollín - Queso crema - Palta - Morrón.',
    price: 10000,
    imageUrl: '/images/products/p3_18.jpg',
    prepTime: 6,
    isAvailable: true,
    isPopular: false,
  },

  // ============================================
  // 🔥 PROMOCIONES ESPECIALES (FRITOS) (c4)
  // ============================================
  {
    id: 'p4_1',
    categoryId: 'c4',
    name: 'Promo 20 Fritos',
    description: '2x Roll Frito (Pollo - Queso crema - Palta).',
    price: 10000,
    imageUrl: '/images/products/p4_1.jpg',
    prepTime: 10,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p4_2',
    categoryId: 'c4',
    name: 'Promo 30 Fritos',
    description: '3x Roll Frito (Pollo - Queso crema - Palta).',
    price: 15000,
    imageUrl: '/images/products/p4_2.jpg',
    prepTime: 12,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p4_3',
    categoryId: 'c4',
    name: 'Promo 40 Fritos',
    description: '4x Roll Frito (Pollo - Queso crema - Palta).',
    price: 18000,
    imageUrl: '/images/products/p4_3.jpg',
    prepTime: 14,
    isAvailable: true,
    isPopular: false,
  },

  // ============================================
  // 👑 PROMOCIONES PREMIUM (c5)
  // ============================================
  {
    id: 'p5_1',
    categoryId: 'c5',
    name: 'Promo 30 Premium',
    description: '1x Roll Frito (Pollo - Queso crema - Palta), 1x Roll Chesse (Camarón - Queso crema - Palta), 1x Roll Avocado (Salmón - Queso crema - Palta).',
    price: 16000,
    imageUrl: '/images/products/p5_1.jpg',
    prepTime: 12,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p5_2',
    categoryId: 'c5',
    name: 'Promo 40 Premium',
    description: '1x Roll Frito (Pollo-Quesocrema-Palta), 1x Roll Avocado (Salmón-Quesocrema-Palta), 1x Roll Chesse (Camarón-Quesocrema-Palta), 1x Roll Sésamo (Kanikama-Quesocrema-Palta).',
    price: 19000,
    imageUrl: '/images/products/p5_2.jpg',
    prepTime: 14,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p5_3',
    categoryId: 'c5',
    name: 'Promo 50 Premium',
    description: '2x Roll Frito (Pollo), 1x Roll Chesse (Camarón), 1x Roll Avocado (Salmón), 1x Roll Sésamo (Kanikama). Todos con Queso crema - Palta.',
    price: 23000,
    imageUrl: '/images/products/p5_3.jpg',
    prepTime: 16,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p5_4',
    categoryId: 'c5',
    name: 'Promo 60 Premium',
    description: '3x Roll Frito (Pollo), 1x Roll Chesse (Camarón), 1x Roll Avocado (Salmón), 1x Roll Sésamo (Kanikama). Todos con Queso crema - Palta.',
    price: 25000,
    imageUrl: '/images/products/p5_4.jpg',
    prepTime: 18,
    isAvailable: true,
    isPopular: false,
  },

  // ============================================
  // 🥢 ARMA TU ROLL (c6)
  // ============================================
  {
    id: 'p6_1',
    categoryId: 'c6',
    name: 'Arma Tu Roll - Sin Arroz',
    description: '1 Envoltura + 2 Proteínas + 2 Agregados. (El precio final lo indicará el local según tus opciones).',
    price: 0,
    imageUrl: '/images/products/p6_1.jpg',
    prepTime: 5,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p6_2',
    categoryId: 'c6',
    name: 'Arma Tu Roll - Con Arroz (Opción 1)',
    description: '1 Envoltura + 1 Proteína + 2 Agregados. (El precio final lo indicará el local según tus opciones).',
    price: 0,
    imageUrl: '/images/products/p6_2.jpg',
    prepTime: 5,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p6_3',
    categoryId: 'c6',
    name: 'Arma Tu Roll - Con Arroz (Opción 2)',
    description: '1 Envoltura + 3 Agregados. Sin Proteína. (El precio final lo indicará el local según tus opciones).',
    price: 0,
    imageUrl: '/images/products/p6_3.jpg',
    prepTime: 5,
    isAvailable: true,
    isPopular: false,
  },

  // ============================================
  // 🏆 CLASI COMBOS (c7)
  // ============================================
  {
    id: 'p7_1',
    categoryId: 'c7',
    name: 'Clasi Combo 1',
    description: 'Handroll Pollo, Strips Pollo Crispy 200gr, Papas Fritas Sobre, Bebida 220cc.',
    price: 10000,
    imageUrl: '/images/products/p7_1.jpg',
    prepTime: 10,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p7_2',
    categoryId: 'c7',
    name: 'Clasi Combo 2',
    description: 'Sushiburger Pollo, Strips Pollo Crispy 200gr, Papas Fritas Sobre, Bebida 220cc.',
    price: 12000,
    imageUrl: '/images/products/p7_2.jpg',
    prepTime: 12,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p7_3',
    categoryId: 'c7',
    name: 'Clasi Combo 3',
    description: '2 Bebida 220cc, 2 Papas Fritas Sobre, Strips Pollo Crispy 400gr, Salsa BBQ 2 Unid.',
    price: 16000,
    imageUrl: '/images/products/p7_3.jpg',
    prepTime: 15,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p7_4',
    categoryId: 'c7',
    name: 'Clasi Combo 4',
    description: 'Bebida 1.5 Litros, Strips Pollo Crispy 400gr, Papas Fritas Mediana, Promo 30 Cortes Premium, 2 Salsas BBQ.',
    price: 32000,
    imageUrl: '/images/products/p7_4.jpg',
    prepTime: 25,
    isAvailable: true,
    isPopular: true,
  },

  // ============================================
  // 🥤 BEBESTIBLES (c8)
  // ============================================
  {
    id: 'p8_1',
    categoryId: 'c8',
    name: 'Té, Café',
    description: 'Té o café caliente.',
    price: 1500,
    imageUrl: '/images/products/p8_1.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_2_coca',
    categoryId: 'c8',
    name: 'Coca-Cola Normal 220cc',
    description: 'Refresco frío mini lata.',
    price: 1500,
    imageUrl: '/images/products/p8_2.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p8_2_zero',
    categoryId: 'c8',
    name: 'Coca-Cola Zero 220cc',
    description: 'Refresco frío mini lata.',
    price: 1500,
    imageUrl: '/images/products/p8_2.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p8_2_fanta',
    categoryId: 'c8',
    name: 'Fanta Normal 220cc',
    description: 'Refresco frío mini lata.',
    price: 1500,
    imageUrl: '/images/products/p8_2.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_2_sprite',
    categoryId: 'c8',
    name: 'Sprite Normal 220cc',
    description: 'Refresco frío mini lata.',
    price: 1500,
    imageUrl: '/images/products/p8_2.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_3_sg',
    categoryId: 'c8',
    name: 'Agua Benedictino Sin Gas',
    description: 'Agua mineral sin gas 500cc.',
    price: 1500,
    imageUrl: '/images/products/p8_3.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_3_cg',
    categoryId: 'c8',
    name: 'Agua Benedictino Con Gas',
    description: 'Agua mineral con gas 500cc.',
    price: 1500,
    imageUrl: '/images/products/p8_3.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_4_coca',
    categoryId: 'c8',
    name: 'Coca-Cola Normal 350cc',
    description: 'Refresco frío en lata normal.',
    price: 2000,
    imageUrl: '/images/products/p8_4.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p8_4_zero',
    categoryId: 'c8',
    name: 'Coca-Cola Zero 350cc',
    description: 'Refresco frío en lata normal.',
    price: 2000,
    imageUrl: '/images/products/p8_4.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'p8_4_fanta',
    categoryId: 'c8',
    name: 'Fanta Normal 350cc',
    description: 'Refresco frío en lata normal.',
    price: 2000,
    imageUrl: '/images/products/p8_4.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_4_sprite',
    categoryId: 'c8',
    name: 'Sprite Normal 350cc',
    description: 'Refresco frío en lata normal.',
    price: 2000,
    imageUrl: '/images/products/p8_4.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_4_inka',
    categoryId: 'c8',
    name: 'Inka Cola 350cc',
    description: 'Refresco frío en lata normal.',
    price: 2000,
    imageUrl: '/images/products/p8_4.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_5',
    categoryId: 'c8',
    name: 'Agua 1.5L',
    description: 'Agua mineral tamaño familiar.',
    price: 2500,
    imageUrl: '/images/products/p8_5.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p8_6',
    categoryId: 'c8',
    name: 'Bebida o Jugo 1.5L',
    description: 'Refresco o jugo tamaño familiar.',
    price: 3000,
    imageUrl: '/images/products/p8_6.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: true,
  },
  
  // ============================================
  // ✨ EXTRAS (c9) - Hidden from main slider
  // ============================================
  {
    id: 'p9_1',
    categoryId: 'c9',
    name: 'Salsa Extra Soya',
    description: 'Porción extra de salsa de soya tradicional.',
    price: 1000,
    imageUrl: '/images/products/sushi-default.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p9_2',
    categoryId: 'c9',
    name: 'Salsa Extra Teriyaki',
    description: 'Porción extra de salsa agridulce teriyaki espesa.',
    price: 1000,
    imageUrl: '/images/products/sushi-default.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p9_3',
    categoryId: 'c9',
    name: 'Salsa Extra Lactonesa',
    description: 'Porción extra de salsa lactonesa casera.',
    price: 1000,
    imageUrl: '/images/products/sushi-default.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  },
  {
    id: 'p9_4',
    categoryId: 'c9',
    name: 'Salsa Extra BBQ',
    description: 'Porción extra de salsa barbacoa.',
    price: 1000,
    imageUrl: '/images/products/sushi-default.jpg',
    prepTime: 0,
    isAvailable: true,
    isPopular: false,
  }
];
